### ISSUE TITLE
No need to any soldering for chinese ones

### ISSUE THREAD

**Issue by mossaudi** [manuelgalindo/MFRC522-UART#1]
just cut 3.3v wire 
also it does not work when soldering the pin to GND

very thanks to your library

**Comment by mfdogalindo** [comment]
enjoy it! XD

**Comment by cyberjupiter** [comment]
So what's the actual configuration? Can you update? I am confused.

**Comment by mfdogalindo** [comment]
@cyberjupiter  first see: https://www.nxp.com/docs/en/data-sheet/MFRC522.pdf
Page 9: Output modes, but remember, this code works in UART mode only.
Page 6: To enable UART mode: I2C(1) pin must be low and EA(32) pin grounded.

**Comment by cyberjupiter** [comment]
Yes I am referring to the datasheet too. I2C pin must be low means that it must be grounded too? Or just cut the connection?

After cutting the I2C bus, I am still getting 3.3V on the I2C pin when measured with ground.
